

CREATE PROCEDURE SP_BNP_INSERIR_PRODUTO 
	@COD_PRODUTO CHAR(4) = 'PRODU',
	@DES_PRODUTO VARCHAR(30) = NULL,
	@STA_STATUS CHAR(1) = 'A'

AS
   
BEGIN   
  BEGIN TRANSACTION    
  

  INSERT INTO PRODUTO(COD_PRODUTO, DES_PRODUTO, STA_STATUS)
	VALUES(@COD_PRODUTO,@DES_PRODUTO, @STA_STATUS)
          
  COMMIT;     
END

GO



--DROP PROCEDURE SP_BNP_CONSULTAR_PRODUTO
-- EXEC SP_BNP_CONSULTAR_PRODUTO
CREATE PROCEDURE SP_BNP_CONSULTAR_PRODUTO 
	@COD_PRODUTO INT = 0,
	@DES_PRODUTO VARCHAR(30) = NULL

AS
   
BEGIN     
	IF(@COD_PRODUTO = 0)
	BEGIN
		SELECT 
			COD_PRODUTO,
			DES_PRODUTO,
			STA_STATUS
		FROM PRODUTO WITH(NOLOCK)
		ORDER BY COD_PRODUTO
	END
	ELSE 
	BEGIN
		SELECT 
			COD_PRODUTO,
			DES_PRODUTO,
			STA_STATUS
		FROM PRODUTO
			WHERE (DES_PRODUTO LIKE '%' + @DES_PRODUTO + '%')
	END
END


GO


-- COSULTAR PRODUTO_COSIF
-- EXEC SP_BNP_CONSULTAR_PRODUTO_COSIF
CREATE PROCEDURE SP_BNP_CONSULTAR_PRODUTO_COSIF
AS
   
BEGIN     
	BEGIN
		SELECT 
			COD_COSIF,
			COD_PRODUTO,
			COD_CLASSIFICACAO,
			STA_STATUS
		FROM PRODUTO_COSIF WITH(NOLOCK)
		ORDER BY COD_PRODUTO
	END
END

GO




CREATE PROCEDURE SP_BNP_INSERIR_MOVIMENTO	
	@DAT_MES INT,
	@DAT_ANO INT,	
	@COD_PRODUTO CHAR(04),
	@COD_COSIF CHAR(11),
	@VAL_VALOR DECIMAL(18,2),
	@DES_DESCRICAO VARCHAR(50)	

AS
   
BEGIN   
  BEGIN TRANSACTION    
  
  DECLARE @NUM_LANCAMENTO INT = (SELECT MAX(NUM_LANCAMENTO) + 1 FROM MOVIMENTO_MANUAL WITH(NOLOCK))
  INSERT INTO MOVIMENTO_MANUAL(
								DAT_MES,
								DAT_ANO,
								NUM_LANCAMENTO,
								COD_PRODUTO,
								COD_COSIF,
								VAL_VALOR,
								DES_DESCRICAO,
								DAT_MOVIMENTO,
								COD_USUARIO)
						VALUES (@DAT_MES,
								@DAT_ANO,
								@NUM_LANCAMENTO,
								@COD_PRODUTO,
								@COD_COSIF,
								@VAL_VALOR,
								@DES_DESCRICAO,
								GETDATE(),
								'TESTE')
          
  COMMIT;     
END

GO

-- exec SP_BNP_CONSULTAR_MOVIMENTO_TODOS
--DROP PROCEDURE SP_BNP_CONSULTAR_MOVIMENTO_TODOS
CREATE PROCEDURE SP_BNP_CONSULTAR_MOVIMENTO_TODOS
AS
BEGIN	
	SELECT M.CODIGO_MOVIMENTO,
			M.DAT_MES,
			M.DAT_ANO,
			M.NUM_LANCAMENTO,
			M.COD_PRODUTO,
			P.DES_PRODUTO AS DESCRICAO_PRODUTO,
			M.COD_COSIF,
			M.VAL_VALOR,
			M.DES_DESCRICAO AS DESCRICAO_MOVIMENTO,
			M.DAT_MOVIMENTO,
			M.COD_USUARIO
	FROM MOVIMENTO_MANUAL M WITH(NOLOCK)
	INNER JOIN PRODUTO P ON P.COD_PRODUTO = M.COD_PRODUTO
	ORDER BY DAT_MES, DAT_ANO, NUM_LANCAMENTO
END